// <auto-generated />
using BankAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240114172418_Added logs")]
    partial class Addedlogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.DBObjects.CryptedAccountData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("CryptedInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "143601139776",
                            CryptedInfo = "pO0nXCjQW+1xQN6hkxPdZ3RvQzGvbcP51a207wGO21DxkFW9A5cMeZTRzdwjhO68KFCuZHhKzOjxFB23PmRS+KptH4751sUJCYoqOcSR7sMG+xnTzy+anC8mp8QbgUT2nMhehcdeuRcU+YjdEdfI1Rf/f5MrE8ZFyZO0MfsLI7mkSRrmG+gskGFsxE+YD+NzNlyNmvS/JH2BA80N7b3mxY1FGtO1Ae7v2vwsU6gneVLsE+1jg+PGOZ2x7ZZa2hwcRVVdIEh4EoYgUvPsNX/QbMcmio7B2t9dQ927I3y7p9OW7NOZ1qU6l2uou4P7E4aJi0OxWrBlr7t1TynnIgjRuSAJS0N2qRyndmT5uBQggh1fIS8+3zrdYpQe5ZKfHhV0M65zToMx5NNKU9S1znDCHXpd6rFsJUmxuJcpJScAr4LDirNk1tFbOqdVGfGR96OFB3uvmOP81A00S/qEmfbbfJtANnhFzE+5gwvSKvQIe5YcA034YgqS6unyU2oFFMCegkt0CpJd04w0SqdDSzJUGUm6QuXHdakEIdHx0JW787PY3NCP8lSvdwkfzy82QQbRnoo1KtYZneneOTClMnWdbc8EFzBgzvuCKVSpIUBKicTIj4hmKEMRpmWJg2qJwhBgt5rNN4rmZyn6PwoQQJgLg1ECStn27sSYTVWi5wKuX699HQNxCcTHYfYusIxUOI5/K5DN9vGdSfmyT4qPSMbL3WfL4lpK6cFvkk6Ql9dFeCGCfr3+093NPiRaqlej5TGyIIdmuaeuBbJ72deqvK41KCUdmnAuzeTrIgXEcbsX+BFByCPi/6Wb7AbSGojeWafB/huxFVUfnn9vW8M49tn5ajoDavnJvgRe/XZKV7fBQlO2lbeKoXYWLd0tTVXq3ZZz",
                            UserName = "BasiaK6"
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "298456755675",
                            CryptedInfo = "fuUakrWUQaiY60G8GfoCa/sTS70eFQgYzYEoxINAWlQtYG1/vIwS7eYbpouqTLZseb3rjUrvmgqWwZ2vzPaIQXEKs8boSwS7XnMrgLRILzQaV+gPO8iBySHS1MkADbKY1kCASaTub1SpZ8jfMRVgmGKxKTfaXjB4IySJmHZvwQx06SkExoeQKH4JaDlm6nUdWROkE0Cl4B2jyYxl4b+XX6jVXzYFy6jHPeUh2qy27PFEaytRM6TRx9FwIW98iDwF9QwAgLgC0JFDIjrdDifBymsrXHWHhCJlsfBO/79fbBPFbvKKgT1bxBpx3zzNAcihFg6Xo19Ny8KaGA4sjbcBfdXAVQfFQRwpmXs1zoGwWMsejtHd8Useea8llPLOJ2us4cSbyndSiRBuPCHNBeP1yNiH8mtHmKIxYIZm8V7Hm2Dx0yWDptrdBTwR6mAGY7xu9qigkT/+SryeD0OMjvQ4hJE85Qo4b3vcNAjdKa+PqSmbI5VTOS9GHRdAvs/p+3hfKn9KweIiN1IukgCcQheh3EthJyc4TEf6mSd7kPzJO+HYmO6CAPO8vXc3myexn9hHIw83eY28txod2+gCmkj4F9oQG/txT4CKcW29i1hkCZZQWakMnWr3jhpMyWjBBJlzOiPbGwMFlVeggzHkbemd+ravPw0D5DKdZWIydEFIUcdCAXUK5Dm4JclElgouW8jUW2AXqmnF6/LLcObs01BwBGmK38RZh3REmL2Srw5HskJcMIGzRRsGyw4TiQYyd2jizYphdWZnGFXpdgngpEOb4PfH+JsYhA3Yt0CNbklMISiGSq+W0ky0DCp0w4ZTJumT+VNIfKl0fqulBkjbPCS09ANxAfXXzKvUQeoYbU+5qCoDLA4MqfeSM77E5v/wxI9AxX7DLQ25i2ao4A005pzoOA==",
                            UserName = "Konon111"
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = "609044535706",
                            CryptedInfo = "t7HikjhObkgt0pWMUe/y4lDoZTO6JpPepsG7kz4REZqqsV7eBfHnfNi4KW4jq/nMYXsKzr4yoiLvGK8Wl/Z7L//0vSQAXLzLFnBKheS2qva4Vvx1gTIcHPo5TSlZ1iydbJnNwI6MoB+4YFs8k3S38AOYGpIUAGFXroiswFZlX4nos04N6aY4fII5t4kOdjUAPT1uuPvXxg1KNd3SLuWAKJYWoOHs3h59UO4OcWslqRNK7S/fumgEEin9BKKReEYoVHpOGcuwE8BfrAj1FCNF3K6gIm5nmM3UrlsN9Gx/Sfv31+kqrpkD5BVdhb9cKZT7kdL7QvzlEhI0c2BTSYoDdu/7En8oB9PwKf87qcIXMV301oLiq51MUK1t68OIdmmF9nGleR3CFwv6VkfcLTsLJcVYHss2mzug16Udgjr4uQhrZuRWJvBSFauCHvNbz6BFBvfTm+MsyaW5meWnrVhUfrzVTTfnAZpGlRWFSypDS0fDuedwQxs/XgU0esWbFDX3BstpltTjCrHOzN6N5oB43v9jB6Th8qQrtXZBfQKKGM5mvsmWxsm0pgXtPpn78xpA3b9WDbd0dwMmQUYtUlWIHctKEOlhiSi010JHWW6aHLPWN+yD8RM/aOMgCIhIV8LXT68fJqNYm7fYDH8ja2YNRVLSoTxFqx0EWYmvT/EbjG6lkznitI/1LJOpO7YlFZEyGX44J6iN1xqVgRTO3fS+3Tu9rvVj1Xewgi6AEd8Pbef/eucD5k5B1Tob6FEKIX4Wb0PqKfnF6QKOBhbCt/m2LuI9FtZWz1VMLwlUBNgNclPzY2LO/83IgQYOapgys29lnptQ7W9KQy+UCGED6zG4/Pd/Yv1TvCS5cR445gZS31n5ql9MCouo4GtN6LAeF/q0",
                            UserName = "Administrator"
                        });
                });

            modelBuilder.Entity("Shared.DBObjects.CryptedAccountStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CryptedInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AccStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CryptedInfo = "hrnR0Hvz9bDBaOqtKTD8T8WHGEl5mJA6Q1i9RE5jKEpJAy1WmVq82kVapmVySwVM7CpDZ3sUfNcW+YrmxrUv2mjdwIYTkQLdyW3kaRHT0olFmSXBOkVmo0BSCZpqRbvE",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CryptedInfo = "hrnR0Hvz9bDBaOqtKTD8T8WHGEl5mJA6Q1i9RE5jKEoWdu6ZpVheZKpOdLru/uCzjQCoAyBdRZ945loCctYJiqILqFvs3aNY+lUw2xN5T/eM7zXl8fBTLZLuH5Qak114",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CryptedInfo = "hrnR0Hvz9bDBaOqtKTD8T8WHGEl5mJA6Q1i9RE5jKEqxoilWwdn2qmydxCShlty7pGs5AFJR1ziZT71XnMPo50AoMIH4DA7Dfb6Hz0kTL1Suc5L1+/obo0YuT0tE45WC",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Shared.DBObjects.CryptedLogData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CryptedInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CryptedInfo = "PPfQrALMIQrHfWui0uoXGXxeXNv6b9MP4OckRNUJjpYrbw592WxQ7ei9jxLRlwMa9OwXcopIFgldUavdXy6HZQGxm2bP4T+PiVhYbs5u1ppcKssEe/y4sUwMIgGNRXwPltjZfEXRbLle4bt8WpmC9Q=="
                        });
                });

            modelBuilder.Entity("Shared.DBObjects.CryptedTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Address")
                        .HasColumnType("int");

                    b.Property<string>("CryptedInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sender")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transfers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = 2,
                            CryptedInfo = "RfEtDRzoOaSuT8BykxYZvRgApNo/Phe9DAcEkA/8v6fioe7MKnSO8A5k39HJ0n/2fuVDISBKZ+brvbor9LSTw7lrmVQi3dY6MEZflh8tSEZMsSkbr5Bm3+Ll9q3538lk",
                            Sender = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = 3,
                            CryptedInfo = "17Ekpj5CXERlXjlD1IJXe04vrjsg91U7X8xvs3gpx1+OWfX3KGTVqI3Bq+4ilavWdDKSJ46HgArhqxhXyycVbhOLxtx7pOHgbUs6fFNV1v7iPVA2TOMNZPrFiRWE8eLC",
                            Sender = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
